-- Seed schema 3 default templates into items
-- Source: docs/_new/Schema Reference 3.0 — Personal OS.md

WITH template_owner AS (
  SELECT id
  FROM auth.users
  ORDER BY created_at ASC
  LIMIT 1
)
INSERT INTO public.items
  (cuid, type, subtype, title, status, access, area, workbench, resources, dependencies, blocked, slug, published, tier, growth, rating, start_date, end_date, date_created, date_modified, date_trashed, tags, content, frontmatter, owner, created_at, updated_at, is_template, medium, format, asset_type, for_sale, sold, exhibited, price, deal_value, lag_target, lag_actual, attendees, total_sent, total_comments, total_responses, chapter_count, series_position, episode, season, date_delivered, contacted_last, next_follow_up, frequency, stack, modules, be_and_feel, chains, platforms, author, bookmark, certificate_link, collection, contact_status, contact_type, course, cover_alt_text, cover_link, currency, currency_primary, currency_secondary, date, deal_status, delivery, description, dimensions, duration_target, genre, institution, instructor, isbn, issue, lag_measure, lag_unit, manuscript, month, month_expenses_chf, month_profit_chf, month_revenue_chf, mood, outcome, platform, principle, problem, project, recording_link, repo, score_overall, series, solution, source, subtitle, target, theme, unit, url, week, year)
VALUES
  (
    'template_journal_daily',
    'journal',
    'daily',
    'Daily',
    'active',
    'paywall',
    NULL,
    false,
    '[]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '## Capture


## Reflection

**Wins:**

**Losses:**

**Lessons:**

**1% better tomorrow:**',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"journal","subtype":"daily","title":"{{date:YYYY-MM-DD}}","status":"active","access":"private","area":null,"workbench":false,"rating":null,"date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_journal_istikarah',
    'journal',
    'istikarah',
    'Istikarah',
    'active',
    'paywall',
    NULL,
    false,
    '[]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '## Intention

What are you seeking guidance on?

## Guidance

What did you receive from Allah SWT?

## Quranic References


## Action

What will you do as a result?

## Signs

#### {{date:YYYY-MM-DD}}

What did you notice and what does it mean?',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"journal","subtype":"istikarah","title":null,"status":"active","access":"private","area":null,"workbench":false,"date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_journal_dream',
    'journal',
    'dream',
    'Dream',
    'active',
    'paywall',
    NULL,
    false,
    '[]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '## Dream


## Symbols


## Reflection

What do you think this dream means?',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"journal","subtype":"dream","title":null,"status":"active","access":"private","area":null,"workbench":false,"mood":null,"rating":null,"date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_journal_scratch',
    'journal',
    'scratch',
    'Scratch',
    'active',
    'paywall',
    NULL,
    false,
    '[]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"journal","subtype":"scratch","title":null,"status":"active","access":"private","area":null,"workbench":false,"date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_journal_devlog',
    'journal',
    'devlog',
    'Devlog',
    'active',
    'paywall',
    NULL,
    false,
    '["[[]]"]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '## What I worked on


## Decisions made


## Blockers


## Next session',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"journal","subtype":"devlog","title":"{{date:YYYY-MM-DD}}","status":"active","access":"private","area":null,"workbench":false,"resources":["[[]]"],"project":"[[]]","series":null,"series_position":null,"date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[[]]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_creation_essay',
    'creation',
    'essay',
    'Essay',
    'active',
    'paywall',
    NULL,
    false,
    '["[[]]"]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    'seedling',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '## Hook


## Body


## Conclusion',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"creation","subtype":"essay","title":null,"subtitle":null,"status":null,"access":"private","area":null,"workbench":false,"resources":["[[]]"],"slug":null,"description":null,"growth":"seedling","tier":null,"cover_link":null,"cover_alt_text":null,"published":false,"date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_creation_framework',
    'creation',
    'framework',
    'Framework',
    'active',
    'paywall',
    NULL,
    false,
    '["[[]]"]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    'seedling',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '## Problem

What problem does this framework solve?

## Framework

### Principle 1


### Principle 2


### Principle 3


## Application

How is this framework applied in real life?

## Example

A concrete example of this framework in action.',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"creation","subtype":"framework","title":null,"subtitle":null,"status":null,"access":"private","area":null,"workbench":false,"resources":["[[]]"],"slug":null,"description":null,"growth":"seedling","tier":null,"published":false,"date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_creation_lesson',
    'creation',
    'lesson',
    'Lesson',
    'active',
    'paywall',
    NULL,
    false,
    '["[[]]"]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    'seedling',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '## Story

Tell the story. Put the reader in the middle of it.

## Insight

What does the story teach?

## Application

How can the reader apply this insight in their own life?',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"creation","subtype":"lesson","title":null,"subtitle":null,"status":null,"access":"private","area":null,"workbench":false,"resources":["[[]]"],"slug":null,"description":null,"growth":"seedling","tier":null,"published":false,"date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_creation_manuscript',
    'creation',
    'manuscript',
    'Manuscript',
    'active',
    'paywall',
    NULL,
    false,
    '["[[]]"]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    'seedling',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '## Premise

What is this manuscript about in one paragraph?

## Audience

Who is this for?

## Structure

How is this manuscript organized?

## Chapters

- [ ] Chapter 1 — [[]]
- [ ] Chapter 2 — [[]]
- [ ] Chapter 3 — [[]]

## Notes

Any additional thoughts, research, or ideas.',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"creation","subtype":"manuscript","title":null,"subtitle":null,"status":null,"access":"private","area":null,"workbench":false,"resources":["[[]]"],"slug":null,"description":null,"genre":null,"medium":null,"growth":"seedling","chapter_count":0,"start_date":null,"end_date":null,"published":false,"tier":null,"cover_link":null,"cover_alt_text":null,"date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_creation_chapter',
    'creation',
    'chapter',
    'Chapter',
    'active',
    'paywall',
    NULL,
    false,
    '["[[]]"]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '## Summary

One paragraph describing what this chapter covers.

## Draft',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"creation","subtype":"chapter","title":null,"subtitle":null,"status":null,"access":"private","area":null,"workbench":false,"resources":["[[]]"],"manuscript":"[[]]","series":null,"series_position":null,"start_date":null,"end_date":null,"published":false,"tier":null,"date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[[]]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_creation_comic',
    'creation',
    'comic',
    'Comic',
    'active',
    'paywall',
    NULL,
    false,
    '["[[]]"]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    'seedling',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '## Premise

What is this issue about in one paragraph?

## Story Beats

-
-
-

## Script

### Page 1

**Panel 1**
- Visual:
- Dialogue:
- Caption:

**Panel 2**
- Visual:
- Dialogue:
- Caption:

## Notes',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"creation","subtype":"comic","title":null,"subtitle":null,"status":null,"access":"private","area":null,"workbench":false,"resources":["[[]]"],"series":null,"series_position":null,"issue":null,"growth":"seedling","start_date":null,"end_date":null,"published":false,"tier":null,"cover_link":null,"cover_alt_text":null,"date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_creation_poem',
    'creation',
    'poem',
    'Poem',
    'active',
    'paywall',
    NULL,
    false,
    '["[[]]"]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    'seedling',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '## Poem


## Notes',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"creation","subtype":"poem","title":null,"subtitle":null,"status":null,"access":"private","area":null,"workbench":false,"resources":["[[]]"],"collection":null,"series":null,"series_position":null,"growth":"seedling","published":false,"tier":null,"cover_link":null,"cover_alt_text":null,"date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_creation_story',
    'creation',
    'story',
    'Story',
    'active',
    'paywall',
    NULL,
    false,
    '["[[]]"]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    'seedling',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '## Premise

What is this story about in one paragraph?

## Story


## Notes',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"creation","subtype":"story","title":null,"subtitle":null,"status":null,"access":"private","area":null,"workbench":false,"resources":["[[]]"],"series":null,"series_position":null,"genre":null,"growth":"seedling","published":false,"tier":null,"cover_link":null,"cover_alt_text":null,"date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_creation_artwork',
    'creation',
    'artwork',
    'Artwork',
    'active',
    'paywall',
    NULL,
    false,
    '["[[]]"]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    'seedling',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '## Description

What is this artwork about?

## Process

How was this made?

## Exhibition History

-

## Notes',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"creation","subtype":"artwork","title":null,"subtitle":null,"status":null,"access":"private","area":null,"workbench":false,"resources":["[[]]"],"series":null,"series_position":null,"medium":null,"dimensions":null,"year":null,"growth":"seedling","for_sale":false,"price":null,"currency":"CHF","sold":false,"exhibited":false,"published":false,"tier":null,"cover_link":null,"cover_alt_text":null,"date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'CHF',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_creation_case_study',
    'creation',
    'case_study',
    'Case Study',
    'active',
    'paywall',
    NULL,
    false,
    '["[[]]"]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    'seedling',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '## Overview

What was this project and why did it matter?

## Challenge

What problem were you solving?

## Process

How did you approach it?

## Outcome

What was the result?

## Lessons

What did you learn?',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"creation","subtype":"case_study","title":null,"subtitle":null,"status":null,"access":"private","area":null,"workbench":false,"resources":["[[]]"],"project":"[[]]","outcome":null,"growth":"seedling","published":false,"tier":null,"cover_link":null,"cover_alt_text":null,"date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[[]]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_creation_workshop',
    'creation',
    'workshop',
    'Workshop',
    'active',
    'paywall',
    NULL,
    false,
    '["[[]]"]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '## Objective

What is the goal of this session?

## Outline

-
-
-

## Materials

-

## Resources

-

## Notes

Post-event additions and observations.',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"creation","subtype":"workshop","title":null,"subtitle":null,"status":null,"access":"private","area":null,"workbench":false,"resources":["[[]]"],"format":null,"series":null,"series_position":null,"platform":null,"date_delivered":null,"attendees":0,"recording_link":null,"published":false,"tier":null,"date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_creation_script',
    'creation',
    'script',
    'Script',
    'active',
    'paywall',
    NULL,
    false,
    '["[[]]"]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '## Hook


## Body


## Call To Action


## Resources

-

## Notes',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"creation","subtype":"script","title":null,"subtitle":null,"status":null,"access":"private","area":null,"workbench":false,"resources":["[[]]"],"format":null,"duration_target":null,"series":null,"series_position":null,"episode":null,"season":null,"recording_link":null,"published":false,"tier":null,"date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_reference_slip',
    'reference',
    'slip',
    'Slip',
    'active',
    'paywall',
    NULL,
    false,
    '[]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '## Note',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"reference","subtype":"slip","title":null,"status":null,"access":"private","area":null,"workbench":false,"source":"[[]]","chains":["[[]]"],"date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '["[[]]"]'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[[]]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_reference_identity',
    'reference',
    'identity',
    'Identity',
    'active',
    'paywall',
    NULL,
    false,
    '[]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '## Content',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"reference","subtype":"identity","title":null,"subtitle":null,"status":null,"access":"private","area":null,"workbench":false,"date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_reference_principle',
    'reference',
    'principle',
    'Principle',
    'active',
    'paywall',
    NULL,
    false,
    '["[[]]"]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '## Principle


## Why',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"reference","subtype":"principle","title":null,"status":null,"access":"private","area":null,"workbench":false,"resources":["[[]]"],"date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_reference_directive',
    'reference',
    'directive',
    'Directive',
    'active',
    'paywall',
    NULL,
    false,
    '["[[]]"]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '## Directive


## Application',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"reference","subtype":"directive","title":null,"status":null,"access":"private","area":null,"workbench":false,"resources":["[[]]"],"principle":"[[]]","date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[[]]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_reference_source',
    'reference',
    'source',
    'Source',
    'active',
    'paywall',
    NULL,
    false,
    '[]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '## Summary

A 1-3 paragraph summary of the source in your own words.

## Key Ideas


## Literature Notes

- [[]]',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"reference","subtype":"source","title":null,"subtitle":null,"status":null,"access":"private","area":null,"workbench":false,"author":"[[]]","medium":null,"url":null,"isbn":null,"start_date":null,"end_date":null,"bookmark":null,"cover_link":null,"cover_alt_text":null,"date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[[]]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_reference_literature',
    'reference',
    'literature',
    'Literature',
    'active',
    'paywall',
    NULL,
    false,
    '[]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '## Notes


## Key Ideas


## Slips

- [[]]',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"reference","subtype":"literature","title":null,"status":null,"access":"private","area":null,"workbench":false,"source":"[[]]","date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[[]]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_reference_quote',
    'reference',
    'quote',
    'Quote',
    'active',
    'paywall',
    NULL,
    false,
    '[]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '>',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"reference","subtype":"quote","title":null,"status":null,"access":"private","area":null,"workbench":false,"author":"[[]]","source":"[[]]","date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[[]]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[[]]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_reference_guide',
    'reference',
    'guide',
    'Guide',
    'active',
    'paywall',
    NULL,
    false,
    '["[[]]"]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '## Overview


## Steps


## Notes',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"reference","subtype":"guide","title":null,"subtitle":null,"status":null,"access":"private","area":null,"workbench":false,"resources":["[[]]"],"published":false,"tier":null,"cover_link":null,"cover_alt_text":null,"date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_reference_offer',
    'reference',
    'offer',
    'Offer',
    'active',
    'paywall',
    NULL,
    false,
    '[]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '## Problem


## Solution


## Value

What transformation does this offer provide?

## Delivery

How is this offer delivered?

## Pricing


## Notes',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"reference","subtype":"offer","title":null,"status":null,"access":"private","area":null,"workbench":false,"problem":null,"solution":null,"price":null,"currency":"CHF","delivery":null,"date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'CHF',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_reference_asset',
    'reference',
    'asset',
    'Asset',
    'active',
    'paywall',
    NULL,
    false,
    '[]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '## Content


## Usage Notes

When and how to use this asset.',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"reference","subtype":"asset","title":null,"status":null,"access":"private","area":null,"workbench":false,"asset_type":null,"date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_reference_software',
    'reference',
    'software',
    'Software',
    'active',
    'paywall',
    NULL,
    false,
    '[]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '## Overview

What does this software do?

## Architecture


## Features

-

## Notes',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"reference","subtype":"software","title":null,"subtitle":null,"status":null,"access":"private","area":null,"workbench":false,"repo":null,"stack":[null],"url":null,"date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[null]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_reference_course',
    'reference',
    'course',
    'Course',
    'active',
    'paywall',
    NULL,
    false,
    '[]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '## Overview

What is this course about?

## Modules

- [ ] [[]]
- [ ] [[]]
- [ ] [[]]

## Key Takeaways


## Notes',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"reference","subtype":"course","title":null,"subtitle":null,"status":null,"access":"private","area":null,"workbench":false,"institution":null,"instructor":null,"url":null,"start_date":null,"end_date":null,"certificate_link":null,"modules":["[[]]"],"date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '["[[]]"]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_reference_module',
    'reference',
    'module',
    'Module',
    'active',
    'paywall',
    NULL,
    false,
    '["[[]]"]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '## Summary


## Key Takeaways


## Notes


## Resources

- [[]]',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"reference","subtype":"module","title":null,"status":null,"access":"private","area":null,"workbench":false,"resources":["[[]]"],"course":"[[]]","series":null,"series_position":null,"date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[[]]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_log_habit',
    'log',
    'habit',
    'Habit',
    'active',
    'paywall',
    NULL,
    false,
    '[]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '| Date | Value | Note |
|------|-------|------|
|      |       |      |',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"log","subtype":"habit","title":null,"status":null,"access":"private","area":null,"workbench":false,"unit":null,"target":null,"frequency":[null],"start_date":null,"end_date":null,"date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[null]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_log_goal',
    'log',
    'goal',
    'Goal',
    'active',
    'paywall',
    NULL,
    false,
    '["[[]]"]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '## Lead Measures

| Date | Lead | Target | Actual | Score | Done | Note |
|------|------|--------|--------|-------|------|------|
|      |      |        |        |       |      |      |

## Weekly Scores

| Week | Score | Lag | On Track | Reflection |
|------|-------|-----|----------|------------|
| 1    |       |     |          |            |
| 2    |       |     |          |            |
| 3    |       |     |          |            |
| 4    |       |     |          |            |
| 5    |       |     |          |            |
| 6    |       |     |          |            |
| 7    |       |     |          |            |
| 8    |       |     |          |            |
| 9    |       |     |          |            |
| 10   |       |     |          |            |
| 11   |       |     |          |            |
| 12   |       |     |          |            |

## EOW Review

**Blocker:**

**Adjustment:**

**Observations:**',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"log","subtype":"goal","title":null,"status":null,"access":"private","area":null,"workbench":false,"resources":["[[]]"],"lag_measure":null,"lag_target":null,"lag_unit":null,"lag_actual":0,"score_overall":null,"start_date":null,"end_date":null,"date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    0,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_log_finance',
    'log',
    'finance',
    'Finance',
    'active',
    'paywall',
    NULL,
    false,
    '[]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '## Revenue

| Date | Client | Offer | Type | Currency | Amount | CHF | Cumulative | Note |
|------|--------|-------|------|----------|--------|-----|------------|------|
|      |        |       |      |          |        |     |            |      |

## Expenses

| Date | Vendor | Category | Currency | Amount | CHF | Cumulative | Note |
|------|--------|----------|----------|--------|-----|------------|------|
|      |        |          |          |        |     |            |      |

## EOD Review

**Rate USD/CHF:**

**Outstanding:**

**Observations:**',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"log","subtype":"finance","title":null,"status":null,"access":"private","area":null,"workbench":false,"date":null,"currency_primary":"CHF","currency_secondary":"USD","month_revenue_chf":0,"month_expenses_chf":0,"month_profit_chf":0,"date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'CHF',
    'USD',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '0',
    '0',
    '0',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_log_contact',
    'log',
    'contact',
    'Contact',
    'active',
    'paywall',
    NULL,
    false,
    '[]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '## Details

- Email:
- Phone:
- Handles:

## Deal

- Title:
- Notes:

## Interactions

#### {{date:YYYY-MM-DD}}

- Channel:
- Summary:
- Next:',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"log","subtype":"contact","title":null,"status":null,"access":"private","area":null,"workbench":false,"contact_type":null,"contact_status":null,"contacted_last":null,"next_follow_up":null,"deal_status":null,"deal_value":null,"date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_log_outreach',
    'log',
    'outreach',
    'Outreach',
    'active',
    'paywall',
    NULL,
    false,
    '[]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '| Name | Platform | Type | Status | Note |
|------|----------|------|--------|------|
|      |          |      |        |      |

## Observations

- Did you update total_* frontmatter fields?
- Did you create contact notes for all promoted rows?
- Any follow-ups to schedule for tomorrow?',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"log","subtype":"outreach","title":null,"status":null,"access":"private","area":null,"workbench":false,"platforms":[null],"total_sent":0,"total_comments":0,"total_responses":0,"date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    0,
    0,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[null]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_review_weekly',
    'review',
    'weekly',
    'Weekly',
    'active',
    'paywall',
    NULL,
    false,
    '["[[]]"]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '## Scores This Week

| Area | Target | Actual | Status |
|------|--------|--------|--------|
|      |        |        |        |

## Wins

What worked and why?

## Losses

What didn''t work and why?

## Key Lessons


## Adjustments for Next Week',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"review","subtype":"weekly","title":null,"status":null,"access":"private","area":null,"workbench":false,"resources":["[[]]"],"week":null,"theme":null,"score_overall":null,"date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_review_monthly',
    'review',
    'monthly',
    'Monthly',
    'active',
    'paywall',
    NULL,
    false,
    '["[[]]"]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '## Scores This Month

| Area | Target | Actual | Status |
|------|--------|--------|--------|
|      |        |        |        |

## Wins

What worked and why?

## Losses

What didn''t work and why?

## Key Lessons


## Adjustments for Next Month',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"review","subtype":"monthly","title":null,"status":null,"access":"private","area":null,"workbench":false,"resources":["[[]]"],"month":null,"score_overall":null,"date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_review_yearly',
    'review',
    'yearly',
    'Yearly',
    'active',
    'paywall',
    NULL,
    false,
    '["[[]]"]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '## Gratitude & Experiences

### I am thankful for...


### I am proud of...


### I overcame...


### People to acknowledge...


### Unique experiences...


## Lessons & Discoveries

### Learned about myself...


### Learned about others...


### Meaningful discoveries...


## Feelings

### Positive feelings to carry forward...


### Negative feelings to let go of...


## Work To Do

### Limiting beliefs...


### What needs to change...


### Envy mapping...


### Current vs desired state...

**Pains of my current state:**

**Joys of my desired state:**

## Next Steps',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"review","subtype":"yearly","title":null,"status":null,"access":"private","area":null,"workbench":false,"resources":["[[]]"],"year":null,"score_overall":null,"date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_review_area',
    'review',
    'area',
    'Area',
    'active',
    'paywall',
    NULL,
    false,
    '["[[]]"]'::jsonb,
    '[]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '## Vision


## Milestones

- [ ]

## Assessment

### Experience


### Problem


### Pain


### Relief


### Reward

## Outcome


**CYCLE 1** —
- Goal: [[]]
- Maintain:

**CYCLE 2** —
- Goal:

**CYCLE 3** —
- Goal:',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"review","subtype":"area","title":null,"status":null,"access":"private","area":null,"workbench":false,"resources":["[[]]"],"be_and_feel":[null],"date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[null]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_action_task',
    'action',
    'task',
    'Task',
    'active',
    'paywall',
    NULL,
    false,
    '[]'::jsonb,
    '["[[]]"]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '## Notes',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"action","subtype":"task","title":null,"status":null,"access":"private","area":null,"workbench":false,"project":"[[]]","dependencies":["[[]]"],"blocked":false,"start_date":null,"end_date":null,"date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[[]]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  ),
  (
    'template_action_project',
    'action',
    'project',
    'Project',
    'active',
    'paywall',
    NULL,
    false,
    '["[[]]"]'::jsonb,
    '["[[]]"]'::jsonb,
    false,
    NULL,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '## Outcome

What does done look like?

## Tasks

- [ ] [[]]
- [ ] [[]]
- [ ] [[]]

## Notes',
    '{"cuid":"{{date:YYYYMMDD}}{{time:HHmmss}}","type":"action","subtype":"project","title":null,"subtitle":null,"status":null,"access":"private","area":null,"workbench":false,"resources":["[[]]"],"dependencies":["[[]]"],"blocked":false,"start_date":null,"end_date":null,"date_created":"{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}","date_modified":null,"date_trashed":null,"tags":null}'::jsonb,
    COALESCE((SELECT id FROM template_owner), NULL),
    now(),
    now(),
    true,
    NULL,
    NULL,
    NULL,
    false,
    false,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  )
ON CONFLICT (cuid) DO UPDATE SET
  type = EXCLUDED.type,
  subtype = EXCLUDED.subtype,
  title = EXCLUDED.title,
  status = EXCLUDED.status,
  access = EXCLUDED.access,
  area = EXCLUDED.area,
  workbench = EXCLUDED.workbench,
  resources = EXCLUDED.resources,
  dependencies = EXCLUDED.dependencies,
  blocked = EXCLUDED.blocked,
  slug = EXCLUDED.slug,
  published = EXCLUDED.published,
  tier = EXCLUDED.tier,
  growth = EXCLUDED.growth,
  rating = EXCLUDED.rating,
  start_date = EXCLUDED.start_date,
  end_date = EXCLUDED.end_date,
  date_created = EXCLUDED.date_created,
  date_modified = EXCLUDED.date_modified,
  date_trashed = EXCLUDED.date_trashed,
  tags = EXCLUDED.tags,
  content = EXCLUDED.content,
  frontmatter = EXCLUDED.frontmatter,
  owner = EXCLUDED.owner,
  updated_at = EXCLUDED.updated_at,
  is_template = EXCLUDED.is_template,
  medium = EXCLUDED.medium,
  format = EXCLUDED.format,
  asset_type = EXCLUDED.asset_type,
  for_sale = EXCLUDED.for_sale,
  sold = EXCLUDED.sold,
  exhibited = EXCLUDED.exhibited,
  price = EXCLUDED.price,
  deal_value = EXCLUDED.deal_value,
  lag_target = EXCLUDED.lag_target,
  lag_actual = EXCLUDED.lag_actual,
  attendees = EXCLUDED.attendees,
  total_sent = EXCLUDED.total_sent,
  total_comments = EXCLUDED.total_comments,
  total_responses = EXCLUDED.total_responses,
  chapter_count = EXCLUDED.chapter_count,
  series_position = EXCLUDED.series_position,
  episode = EXCLUDED.episode,
  season = EXCLUDED.season,
  date_delivered = EXCLUDED.date_delivered,
  contacted_last = EXCLUDED.contacted_last,
  next_follow_up = EXCLUDED.next_follow_up,
  frequency = EXCLUDED.frequency,
  stack = EXCLUDED.stack,
  modules = EXCLUDED.modules,
  be_and_feel = EXCLUDED.be_and_feel,
  chains = EXCLUDED.chains,
  platforms = EXCLUDED.platforms,
  author = EXCLUDED.author,
  bookmark = EXCLUDED.bookmark,
  certificate_link = EXCLUDED.certificate_link,
  collection = EXCLUDED.collection,
  contact_status = EXCLUDED.contact_status,
  contact_type = EXCLUDED.contact_type,
  course = EXCLUDED.course,
  cover_alt_text = EXCLUDED.cover_alt_text,
  cover_link = EXCLUDED.cover_link,
  currency = EXCLUDED.currency,
  currency_primary = EXCLUDED.currency_primary,
  currency_secondary = EXCLUDED.currency_secondary,
  date = EXCLUDED.date,
  deal_status = EXCLUDED.deal_status,
  delivery = EXCLUDED.delivery,
  description = EXCLUDED.description,
  dimensions = EXCLUDED.dimensions,
  duration_target = EXCLUDED.duration_target,
  genre = EXCLUDED.genre,
  institution = EXCLUDED.institution,
  instructor = EXCLUDED.instructor,
  isbn = EXCLUDED.isbn,
  issue = EXCLUDED.issue,
  lag_measure = EXCLUDED.lag_measure,
  lag_unit = EXCLUDED.lag_unit,
  manuscript = EXCLUDED.manuscript,
  month = EXCLUDED.month,
  month_expenses_chf = EXCLUDED.month_expenses_chf,
  month_profit_chf = EXCLUDED.month_profit_chf,
  month_revenue_chf = EXCLUDED.month_revenue_chf,
  mood = EXCLUDED.mood,
  outcome = EXCLUDED.outcome,
  platform = EXCLUDED.platform,
  principle = EXCLUDED.principle,
  problem = EXCLUDED.problem,
  project = EXCLUDED.project,
  recording_link = EXCLUDED.recording_link,
  repo = EXCLUDED.repo,
  score_overall = EXCLUDED.score_overall,
  series = EXCLUDED.series,
  solution = EXCLUDED.solution,
  source = EXCLUDED.source,
  subtitle = EXCLUDED.subtitle,
  target = EXCLUDED.target,
  theme = EXCLUDED.theme,
  unit = EXCLUDED.unit,
  url = EXCLUDED.url,
  week = EXCLUDED.week,
  year = EXCLUDED.year
;